comment:
  image:
    repository: antonritter85/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: antonritter85/post
    tag: latest
    service:
      externalPort: 5000

ui:
  image:
    repository: antonritter85/ui
    tag: latest
    service:
      externalPort: 9292
