version: '3'
services:
  fluentd:
    image: ${USERNAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - front_net

  elasticsearch:
    image: elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      - front_net

  kibana:
    image: kibana
    ports:
      - "5601:5601"
    networks:
      - front_net

networks:
  front_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24