{
 "title": "Docker_Telegraf_Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPUs Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "docker_n_cpus" }
   ]
  },
  {
   "title": "Memory total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "decmbytes",
   "valueName": "avg",
   "targets": [
    { "expr": "docker_memory_total/(1024^2)" }
   ]
  },
  {
   "title": "All Docker Containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "docker_n_containers" }
   ]
  },
  {
   "title": "Running Docker Containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "docker_n_containers_running" }
   ]
  },
  {
   "title": "Docker images count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "docker_n_images" }
   ]
  },
  {
   "title": "CPU Usage per Container, %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent",
     "legendFormat": "{{com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "docker_container_mem_usage/(1024*1024)",
     "legendFormat": "{{com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Docker Containers Network RX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "docker_container_net_rx_bytes/(1024^3)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Docker Containers Network RX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "docker_container_net_tx_bytes/(1024^3)"
    }
   ]
  }
 ]
}