groups:
  - name: alert.rules
    rules:
    - alert: InstanceDown
      expr: up == 0
      for: 1m
      labels:
        severity: page
      annotations:
        description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute'
        summary: 'Instance {{ $labels.instance }} down'
    - alert: PercentileLatency
      expr: |
        histogram_quantile(0.95, sum(rate(ui_request_latency_seconds_bucket[5m])) by (le)) > 0.065
      for: 1m
      labels:
        severity: page
      annotations:
        description: 'Latency for request {{ $labels.path }} more then 95th Percentile'
        summary: 'Latency for request more than 0.065 sec'
