kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: 0JMRFVOyIKBNdEapAhqU9TMEjYcJYMHFGqH9DpiU9WU=
      - identity: {}
