---
- name: Install Docker Engine and Docker Compose
  hosts: all
  become: true

  tasks:

    - name: Install prerequisites for Docker and python-pip
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - software-properties-common
        - python-pip
      tags: install

    - name: Add an Apt signing key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        id: 0EBFCD88
      tags: install
      
    - name: Add docker repository into sources list
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
        state: present
      tags: install
      
    - name: Install docker-ce
      apt:
        name: docker-ce
        state: present
        update_cache: yes
      tags: install
      
    - name: Enable docker service
      systemd:
        name: docker
        enabled: yes
        state: started
      tags: install

    - name: Install Python library for the Docker Engine API and Docker Compose
      pip:
        name: "{{ item }}"
      loop:
        - docker
        - docker-compose
      tags: install
